### ISSUE TITLE
Can sharedrop work in the company intranet?

### ISSUE THREAD

**Issue by Shuai-Xie** [szimek/sharedrop#106]
My company has two Wi-Fis, **A** for employees and **A_Guest** for guests.

I try to send files from **device 1 using A_Guest** to **device 2 using A**, but the file transfer seems not working and the blue signal light is flashing all the time.

![QQ截图20210325105200.png](https://upload-images.jianshu.io/upload_images/1877813-0cde4307f46ac937.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

I've also tried files with different sizes or formats, but it's still not working.

Please give me a hand. Thanks very much.

**Comment by davidak** [comment]
I guess the two networks don't have access to each other for security reasons. So, you have to go through the internet.
It totally depends on what the network allows. Maybe WebRTC is blocked in the company network.

So, best would be to talk to the networks admins if there are any reasons why this can not work. I think generally it should work, when the connection is not blocked on purpose.

**Comment by clodsch** [comment]
In our school network, the transfer of files with sharedrop works with 2 devices connected to the same WiFi, whereas it doesn't always work between a PC connected to our school LAN an an iPad (both having a similar IP adress). Sometimes it works, sometimes not.
![sharedropError](https://user-images.githubusercontent.com/85510413/121058322-83928d00-c7c0-11eb-9738-fe240bb55c98.jpeg) What could cause the problem?

**Comment by falktan** [comment]
@clodsch There could be many reasons. For instance there might be different subnets and it only works if both devices happen to be placed in the same subnet.

**Comment by falktan** [comment]
I would suggest to close this issue, as there does not seem to be much that can be done in this repo. The connectivity in company networks depends mostly on how this network is configured and what it allows.

**Comment by szimek** [comment]
I admit there should be a better error handling and communication - blinking blue light is not the best way to communicate that something went wrong...

The popup with the error message could also look a bit nicer.

However, the underlying issue, i.e. that in some cases it's not possible to establish a direct peer-to-peer connection could be "fixed" by introducing a TURN server. However, it costs a lot and Sharedrop doesn't bring any money, so that's why it does use one.

If anyone knows a company that provides TURN servers a service and would like to sponsor one for Sharedrop, please let me know :)
